security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            pattern:    ^/
            #form_registration:
            #    registration_path: registration
            #    check_path: registration
            form_login:
                login_path: login
                check_path: login
            provider: db_provider
            logout:
                path:   /
                target: /
    access_control:
                - { path: ^/login, roles: ROLE_ADMIN }
                - { path: ^/registration, roles: ROLE_ADMIN }